---
abstract: 'the HTTP client for dealing with complex WEB API.'
author:
  - 'mizuki_r <ry.mizuki@gmail.com>'
build_requires:
  Test::Fake::HTTPD: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.5, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spica
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Spica:
    file: lib/Spica.pm
    version: 0.04
  Spica::Client:
    file: lib/Spica/Client.pm
    version: 0
  Spica::Event:
    file: lib/Spica/Event.pm
    version: 0
  Spica::Filter:
    file: lib/Spica/Filter.pm
    version: 0
  Spica::Parser:
    file: lib/Spica/Parser.pm
    version: 0
  Spica::Parser::JSON:
    file: lib/Spica/Parser/JSON.pm
    version: 0
  Spica::Parser::XML:
    file: lib/Spica/Parser/XML.pm
    version: 0
  Spica::Receiver::Iterator:
    file: lib/Spica/Receiver/Iterator.pm
    version: 0
  Spica::Receiver::Row:
    file: lib/Spica/Receiver/Row.pm
    version: 0
  Spica::Spec:
    file: lib/Spica/Spec.pm
    version: 0
  Spica::Spec::Declare:
    file: lib/Spica/Spec/Declare.pm
    version: 0
  Spica::Trigger:
    file: lib/Spica/Trigger.pm
    version: 0
  Spica::Types:
    file: lib/Spica/Types.pm
    version: 0
  Spica::URIMaker:
    file: lib/Spica/URIMaker.pm
    version: 0
requires:
  Carp: 1.08
  Class::Load: 0.06
  Clone: 0.28
  Data::Validator: 0.09
  Exporter::Lite: 0.02
  Furl: 0.20
  JSON: 2.15
  Mouse: 0.93
  MouseX::Types: 0.01
  Scalar::Util: 0
  URI: 1.40
  XML::Simple: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/rymizuki/p5-Spica/issues
  homepage: https://github.com/rymizuki/p5-Spica
  repository: git://github.com/rymizuki/p5-Spica.git
version: 0.04
